# Generated by Django 2.2.16 on 2021-11-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0002_auto_20211102_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre_title',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='title_id',
            new_name='title',
        ),
    ]
