# Generated by Django 2.2.16 on 2021-11-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_titles_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genre_title',
            name='genre_titles',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(through='reviews.Genre_title', to='reviews.Genre'),
        ),
        migrations.AddConstraint(
            model_name='genre_title',
            constraint=models.UniqueConstraint(fields=('title', 'genre'), name='genre_titles'),
        ),
    ]
